name: Publish Python Package to PyPI

on:
  release:
    types: [published, released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Read VERSION and REQUIREMENTS
      run: |
        echo 'VERSION<<EOF' >> $GITHUB_ENV
        echo $(cat VERSION.txt) >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        
        echo 'REQUIREMENTS<<EOF' >> $GITHUB_ENV
        echo $(cat requirements.txt) >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
