name: Sync Main to Dev

on:
  push:
    branches:
      - main

jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge Main into Dev
        run: |
          git checkout dev  
          git merge main --no-ff -m "Sync Main to Dev"
